export const VISIBLE_SORT = 'VISIBLE_SORT'
export const VISIBLE_SUB_CATEGORY = 'VISIBLE_SUB_CATEGORY'
export const CATEGORIES_FETCHED = 'CATEGORIES_FETCHED'
export const CATEGORIES_FAILED = 'CATEGORIES_FAILED'

