//VISIBILITIES
export const VISIBLE_SORT = 'VISIBLE_SORT'
export const VISIBLE_SUB_CATEGORY = 'VISIBLE_SUB_CATEGORY'
export const VISIBLE_SEARCH_RESULT = 'VISIBLE_SEARCH_RESULT'

//CATALOG
export const CATEGORIES_FETCHED = 'CATEGORIES_FETCHED'
export const CATEGORIES_FAILED = 'CATEGORIES_FAILED'

export const SUB_CATEGORIES_FETCHED = 'SUB_CATEGORIES_FETCHED'
export const SUB_CATEGORIES_FAILED = 'SUB_CATEGORIES_FAILED'

export const PLACES_FETCHED = 'PLACES_FETCHED'
export const PLACES_FAILED = 'PLACES_FAILED'

export const TOP_PLACES_FETCHED = 'TOP_PLACES_FETCHED'
export const TOP_PLACES_FAILED = 'TOP_PLACES_FAILED'

//SEARCH_CATALOG
export const SEARCH_FETCHED = 'SEARCH_FETCHED'
export const SEARCH_FAILED = 'SEARCH_FAILED'

export const SEARCH_TEXT_CHANGE = 'SEARCH_TEXT_CHANGE'

//SELECT_DIR_CATALOG
export const SELECT_DIR_CATALOG = 'SELECT_DIR_CATALOG'

//SELECT_SUB_CATALOG
export const SELECT_SUB_CATALOG = 'SELECT_SUB_CATALOG'

//FAVORITE
export const FAV_PLACE_FETCHED = 'FAV_PLACE_FETCHED'
export const FAV_PLACE_FAILED = 'FAV_PLACE_FAILED'
export const FAV_SALE_FETCHED = 'FAV_SALE_FETCHED'
export const FAV_SALE_FAILED = 'FAV_SALE_FAILED'
//SELECT_HORIZONTAL_FAVORITE
export const SELECT_HORIZONTAL_FAVORITE = 'SELECT_HORIZONTAL_FAVORITE'

//ITEM
export const ITEM_FETCHED = 'ITEM_FETCHED'
export const ITEM_FAILED = 'ITEM_FAILED'
export const ITEM_PLACES_FETCHED = 'ITEM_PLACES_FETCHED'
export const ITEM_PLACES_FAILED = 'ITEM_PLACES_FAILED'
export const SEARCH_PLACE_CHANGE = 'SEARCH_PLACE_CHANGE'

//SELECT_DIR_ITEM
export const SELECT_DIR_ITEM = 'SELECT_DIR_ITEM'
//SELECT_HORIZONTAL_ITEM
export const SELECT_HORIZONTAL_ITEM = 'SELECT_HORIZONTAL_ITEM'

//SALE
export const SALE_FETCHED = 'SALE_FETCHED'
export const SALE_FAILED = 'SALE_FAILED'

//CITY
export const CITY_FETCHED = 'CITY_FETCHED'
export const CITY_FAILED = 'CITY_FAILED'
export const CITY_SELECT = 'CITY_SELECT'

//PROMO
export const PROMO_1_FETCHED = 'PROMO_1_FETCHED'
export const PROMO_2_FETCHED = 'PROMO_2_FETCHED'
export const PROMO_FAILED = 'PROMO_FAILED'
