export const VISIBLE_SORT = 'VISIBLE_SORT'
export const VISIBLE_SUB_CATEGORY = 'VISIBLE_SUB_CATEGORY'
export const CATEGORIES_FETCHED = 'CATEGORIES_FETCHED'
export const CATEGORIES_FAILED = 'CATEGORIES_FAILED'
export const SUB_CATEGORIES_FETCHED = 'SUB_CATEGORIES_FETCHED'
export const SUB_CATEGORIES_FAILED = 'SUB_CATEGORIES_FAILED'
export const PLACES_FETCHED = 'PLACES_FETCHED'
export const PLACES_FAILED = 'PLACES_FAILED'

